### ISSUE TITLE
Setup Buildroot build for client

### ISSUE THREAD

**Issue by anuh7** [anuh7/final-project-assignment-anuh#3]
DoD: Create a build root repository for the Autonomous monitoring system, target hardware Raspberry pi.
Blockers: none

**Comment by malolasimman** [comment]
Successfully, built the buildroot image for client side, flashed and boot up a image for RaspberryPi 3b+.
 Blockers: none
buildroot Repo link for client side   [Click here](https://github.com/cu-ecen-aeld/final-project-malolasimman)
commit id 8737aacaa4d98d3447f94a656f85f51d815aeb9e

Buildroot image Bootup in Raspberry Pi3


![Image](https://user-images.githubusercontent.com/59477885/232626994-f7c76e6f-a58b-4f3c-8af2-42d665f23ecb.jpeg)
